package com.test;
public class Ex09_4 {

	public static void main(String[] args) {
		System.out.println("시작");
		String name = null;
	try {
		int num = 3 / 0;
		System.out.println("결과값 :" + num);
	}catch(ArithmeticException e) { // 딱 맞는 타입의 exception캐치문을 잡아야함.
		System.out.println(e.getMessage());
	}finally{
		System.out.println("반드시 수행되는 문장");
	}	
	System.out.println("프로그램 정상 종료");	
	}
}
